parameters:
    Sewolabs_user_security.component.authentication.handler.login_success_handler.class: Sewolabs\UserBundle\Component\Authentication\Handler\LoginFailureHandler
    Sewolabs_user_security.component.authentication.handler.logout_success_handler.class: Sewolabs\UserBundle\Component\Authentication\Handler\LogoutSuccessHandler
    
services:
    Sewolabs_user_security.component.authentication.handler.login_success_handler:
        class:  %Sewolabs_user_security.component.authentication.handler.login_success_handler.class%
        arguments:  [@service_container, @router, @security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' } 
    Sewolabs_user_security.component.authentication.handler.logout_success_handler:
        class:  %Sewolabs_user_security.component.authentication.handler.logout_success_handler.class%
        arguments:  [@service_container, @router]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    sewolabs_user.profile.form.type:
        class: Sewolabs\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fos_user_profile }
    sewolabs_user.registration.form.type:
        class: Sewolabs\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fos_user_registration }
    sewolabs_user.resetting.form.type:
        class: Sewolabs\UserBundle\Form\Type\ResettingFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: fos_user_resetting }